#!/bin/bash

# Senti-Core React - File Structure Overview

echo "📦 SENTI-CORE REACT PROJECT STRUCTURE"
echo "======================================"
echo ""

echo "🎯 REACT FRONTEND (New!)"
echo "├── src/"
echo "│   ├── main.jsx                 ⚛️  React entry point"
echo "│   ├── App.jsx                  🎮 Main app component (state management)"
echo "│   ├── App.css                  🎨 Global app styles"
echo "│   ├── index.css                📄 Base styles"
echo "│   └── components/"
echo "│       ├── Hero.jsx             🦸 Landing hero section"
echo "│       ├── Hero.css"
echo "│       ├── AnalysisForm.jsx     📝 Input form with validation"
echo "│       ├── AnalysisForm.css"
echo "│       ├── Loading.jsx          ⏳ Loading with agent progress"
echo "│       ├── Loading.css"
echo "│       ├── Results.jsx          📊 Results display container"
echo "│       ├── Results.css"
echo "│       ├── SentimentGauge.jsx   📈 Animated sentiment gauge"
echo "│       ├── SentimentGauge.css"
echo "│       ├── AgentCard.jsx        🃏 Individual agent reports"
echo "│       ├── AgentCard.css"
echo "│       ├── ParticleBackground.jsx ✨ Canvas particle system"
echo "│       └── ParticleBackground.css"
echo ""

echo "⚙️ CONFIGURATION"
echo "├── package.json                 📦 npm dependencies & scripts"
echo "├── vite.config.js               ⚡ Vite configuration & proxy"
echo "├── index.html                   🌐 React entry HTML"
echo "└── .gitignore                   🚫 Git ignore rules"
echo ""

echo "🔧 BACKEND (Unchanged)"
echo "├── crewgooglegemini/"
echo "│   ├── agents.py                🤖 Three AI agents"
echo "│   ├── tasks.py                 📋 Agent tasks"
echo "│   ├── endpoints.py             🚀 FastAPI routes (CORS enabled)"
echo "│   └── tools.py                 🛠️  Agent tools"
echo ""

echo "📚 DOCUMENTATION"
echo "├── REACT_MIGRATION.md           📘 Quick start guide (READ THIS FIRST!)"
echo "├── REACT_GUIDE.md               📗 Comprehensive React docs"
echo "├── SENTI_CORE_GUIDE.md          📙 Backend API docs"
echo "├── GREEN_THEME.md               🎨 Theme design system"
echo "├── TRANSFORMATION.md            📊 Before/after comparison"
echo "└── README.md                    📖 Original README"
echo ""

echo "🚀 START SCRIPTS"
echo "├── start_react.sh               ⚛️  Start React + Backend (NEW!)"
echo "├── start_senticore.sh           🐍 Start backend only"
echo "└── start.sh                     📄 Start vanilla version"
echo ""

echo "📂 LEGACY (Backup)"
echo "└── static/                      💾 Original vanilla JS version"
echo "    ├── index.html"
echo "    ├── styles.css"
echo "    └── script.js"
echo ""

echo "✅ PROJECT STATUS: READY"
echo "======================================"
echo ""
echo "🎯 TO START THE APP:"
echo "   1. npm install              (install dependencies)"
echo "   2. ./start_react.sh         (start everything)"
echo "   3. Open http://localhost:3000"
echo ""
echo "📚 FOR HELP:"
echo "   Read REACT_MIGRATION.md for quick start"
echo "   Read REACT_GUIDE.md for detailed docs"
echo ""
